export const styles = {
  footerWrapper: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    justifyContent: 'center',
    padding: '0 2rem 1rem 2rem',
    zIndex: 100,
    pointerEvents: 'none',
  },
  footerContainerCompact: {
    backgroundColor: '#ffffff',
    borderTop: '1px solid var(--border-light)',
    width: '100%',
    pointerEvents: 'auto',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    boxShadow: '0 -4px 6px -1px rgba(0, 0, 0, 0.05)',
  },
  footerContainerExpanded: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    boxShadow: '0 20px 50px -12px rgba(15, 23, 42, 0.15)',
    border: '1px solid var(--border-light)',
    width: '100%',
    maxWidth: '1000px',
    pointerEvents: 'auto',
    position: 'relative',
    marginBottom: '1rem',
  },
  compactBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '0.75rem 2rem',
  },
  compactLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '2rem',
  },
  miniItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  miniIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniLabel: {
    fontSize: '0.65rem',
    color: 'var(--text-secondary)',
    fontWeight: '600',
  },
  miniValue: {
    fontSize: '0.9rem',
    fontWeight: '800',
    color: 'var(--text-primary)',
  },
  compactRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  totalLabel: {
    fontSize: '0.7rem',
    fontWeight: '600',
    color: 'var(--text-secondary)',
  },
  totalValue: {
    fontSize: '1.25rem',
    fontWeight: '800',
    color: 'var(--accent-teal)',
    lineHeight: '1',
  },
  toggleBtn: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: 'var(--bg-light-gray)',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  toggleBtnAbsolute: {
    position: 'absolute',
    top: '1.5rem',
    right: '1.5rem',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: 'var(--bg-light-gray)',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
  },
  expandedContent: {
    padding: '2rem',
  },
  summaryHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '2rem',
  },
  summaryTitle: {
    fontSize: '1.5rem',
    fontWeight: '800',
    color: '#020617',
    margin: 0,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
    marginBottom: '2rem',
  },
  costCard: {
    backgroundColor: '#f8fafc',
    padding: '1.5rem',
    borderRadius: '12px',
    border: '1px solid var(--border-light)',
  },
  iconBoxTop: {
    marginBottom: '1rem',
  },
  costLabelCard: {
    fontSize: '0.85rem',
    color: 'var(--text-secondary)',
    fontWeight: '500',
    marginBottom: '0.5rem',
  },
  costValueCard: {
    fontSize: '1.35rem',
    fontWeight: '800',
    color: '#0f172a',
  },
  expandedDivider: {
    height: '1px',
    backgroundColor: 'var(--border-light)',
    marginBottom: '1.5rem',
  },
  expandedTotalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  expandedTotalLabel: {
    fontSize: '1.1rem',
    fontWeight: '800',
    color: '#0f172a',
  },
  expandedTotalValue: {
    fontSize: '2rem',
    fontWeight: '800',
    color: 'var(--accent-teal)',
  }
};
