export const styles = {
  hero: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flex: 1,
    position: 'relative',
    backgroundColor: 'transparent',
    width: '100%',
    padding: '2rem 0 5rem 0',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    zIndex: 10,
    maxWidth: '1800px',
    padding: '0 2rem 2rem 2rem',
    position: 'relative',
    justifyContent: 'space-between',
    width: '100%',
  },
  topSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: '1rem',
    marginBottom: '0',
    justifyContent: 'center',
    width: '100%',
  },
  title: {
    fontSize: 'clamp(2.5rem, 8vw, 5.5rem)',
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: '-0.04em',
    maxWidth: '1200px',
    lineHeight: '1.05',
    marginBottom: '1.5rem',
    color: 'var(--text-primary)',
    textShadow: '0 2px 10px rgba(255,255,255,0.5)',
  },
  accentText: {
    color: 'var(--accent-teal)',
    fontStyle: 'italic',
  },
  taglineWrapper: {
    display: 'inline-block',
    minHeight: '1.2em',
  },
  buttonGroup: {
    display: 'flex',
    gap: '1rem',
    marginTop: '0.5rem',
  },
  primaryButton: {
    backgroundColor: 'var(--accent-teal)',
    color: '#fff',
    padding: '1.1rem 2.5rem',
    borderRadius: '99px',
    fontSize: '1.1rem',
    fontWeight: '700',
    border: '2px solid rgba(255, 255, 255, 0.9)',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    cursor: 'pointer',
  },
  destinationsSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginTop: '0rem',
    width: '100%',
    maxWidth: '1750px',
  },
  sectionTitleCenter: {
    fontSize: '1.5rem',
    fontWeight: '800',
    color: 'var(--accent-teal)',
    backgroundColor: '#ffffff',
    backdropFilter: 'blur(12px)',
    padding: '0.8rem 2rem',
    borderRadius: '99px',
    marginBottom: '2rem',
    display: 'inline-block',
    border: '1px solid rgba(5, 150, 105, 0.2)',
    boxShadow: '0 10px 25px -5px rgba(0,0,0,0.1)',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  destinationGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '2rem',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '1750px',
  },
  destCard: {
    flex: '1 1 350px',
    maxWidth: '500px',
    height: '460px',
    borderRadius: '32px',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    cursor: 'pointer',
  },
  imageContainer: {
    width: '100%',
    flex: 1,
    borderRadius: '24px',
    marginBottom: '1.5rem',
    overflow: 'hidden',
    boxShadow: '0 10px 30px rgba(0,0,0,0.1)',
  },
  destImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.5s ease',
  },
  textWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '60px',
  },
  destName: {
    fontSize: '1.75rem',
    fontWeight: '800',
    color: 'var(--text-primary)',
    lineHeight: '1.1',
  },
  destTagline: {
    fontSize: '1rem',
    fontWeight: '600',
    color: 'var(--text-tertiary)',
    lineHeight: '1.1',
    marginTop: '0.3rem',
  },
  newsSection: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    margin: '1rem 0',
  },
  newsPill: {
    display: 'flex',
    alignItems: 'center',
    padding: '0.8rem 2.5rem',
    borderRadius: '99px',
    gap: '1.5rem',
    maxWidth: '900px',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    border: '1px solid rgba(255, 255, 255, 0.6)',
  },
  newsLabel: {
    fontSize: '0.85rem',
    fontWeight: '800',
    color: 'var(--accent-teal)',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    whiteSpace: 'nowrap',
  },
  newsLine: {
    width: '1px',
    height: '20px',
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  newsText: {
    fontSize: '1rem',
    fontWeight: '600',
    color: 'var(--text-primary)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  }
};
