export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    flex: 1,
    position: 'relative',
    backgroundColor: 'transparent',
    width: '100%',
    padding: '3rem 0 5rem 0',
  },
  content: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    maxWidth: '1200px',
    padding: '0 2rem',
  },
  headerBox: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    marginBottom: '3rem'
  },
  title: {
    fontSize: 'clamp(2.5rem, 5vw, 4rem)',
    fontWeight: '800',
    color: 'var(--text-primary)',
    marginBottom: '0.5rem',
    textShadow: '0 2px 10px rgba(255,255,255,0.7)',
  },
  tagline: {
    fontSize: '1.2rem',
    fontWeight: '600',
    color: 'var(--accent-teal)',
    textTransform: 'uppercase',
    letterSpacing: '0.1em'
  },
  tabContainer: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
    marginBottom: '3rem',
  },
  tabTrack: {
    display: 'flex',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: '99px',
    padding: '0.5rem',
    gap: '0.5rem',
  },
  tabButton: {
    padding: '1rem 2rem',
    borderRadius: '99px',
    fontSize: '1.05rem',
    fontWeight: '700',
    color: 'var(--text-secondary)',
    backgroundColor: 'transparent',
    transition: 'all 0.3s ease',
  },
  activeTab: {
    backgroundColor: '#fff',
    color: 'var(--accent-teal)',
    boxShadow: '0 4px 15px rgba(0,0,0,0.05)',
  },
  contentArea: {
    width: '100%',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(450px, 1fr))',
    gap: '2rem',
    width: '100%',
  },
  card: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: '1.5rem 2rem',
    borderRadius: '24px',
    gap: '1.5rem',
  },
  cardIcon: {
    fontSize: '2rem',
    lineHeight: '1',
    paddingTop: '0.2rem',
  },
  cardContent: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: '0.5rem',
  },
  cardTitle: {
    fontSize: '1.15rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
  },
  cardTime: {
    fontSize: '0.85rem',
    fontWeight: '600',
    color: 'var(--accent-teal)',
    whiteSpace: 'nowrap',
    marginLeft: '1rem',
  },
  cardDesc: {
    fontSize: '1rem',
    color: 'var(--text-secondary)',
    lineHeight: '1.5',
  },
  statusBox: {
    display: 'flex',
    flexDirection: 'column',
    borderRadius: '24px',
    padding: '1rem 2rem',
    maxWidth: '900px',
    margin: '0 auto',
  },
  statusRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1.5rem 0',
  },
  statusLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
  },
  statusIndicator: {
    width: '14px',
    height: '14px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  destName: {
    fontSize: '1.15rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
    minWidth: '150px',
  },
  destInfo: {
    fontSize: '1rem',
    fontWeight: '600',
    textAlign: 'right',
  }
};
