export const styles = {
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '1.5rem 4rem',
    backgroundColor: 'var(--bg-color)',
    borderBottom: '1px solid var(--border-light)',
    height: '80px',
    flexShrink: 0,
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1000,
  },
  logoLink: {
    textDecoration: 'none',
    color: 'inherit',
  },
  logoImage: {
    height: '45px',
    width: 'auto',
    display: 'block',
    transition: 'opacity 0.2s',
  },
  nav: {
    display: 'flex',
    gap: '1rem',
    alignItems: 'center',
    marginLeft: 'auto',
    marginRight: '2.5rem',
  },
  navLink: {
    fontSize: '0.9rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
    backgroundColor: 'var(--glass-bg)',
    backdropFilter: 'blur(10px)',
    padding: '0.6rem 1.5rem',
    borderRadius: '99px',
    border: '1px solid var(--glass-border)',
    transition: 'all 0.3s ease',
    whiteSpace: 'nowrap',
  },
  navLinkHover: {
    color: 'var(--accent-teal)',
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
  },
  loginButton: {
    padding: '0.5rem 1.25rem',
    backgroundColor: 'transparent',
    color: 'var(--text-primary)',
    fontWeight: '600',
    fontSize: '1rem',
    borderRadius: '99px',
    border: '1px solid var(--border-light)',
    transition: 'all 0.2s',
  },
  themeToggle: {
    background: 'var(--glass-bg)',
    border: '1px solid var(--glass-border)',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.2rem',
    marginRight: '1rem',
    cursor: 'pointer',
    color: 'var(--text-primary)',
    transition: 'all 0.3s ease',
  },
  hamburger: {
    display: 'none',
    flexDirection: 'column',
    gap: '5px',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '5px',
    zIndex: 100,
  },
  burgerLine: {
    width: '25px',
    height: '2px',
    backgroundColor: 'var(--text-primary)',
    transition: 'all 0.3s',
  },
  mobileOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    backgroundColor: 'var(--overlay-bg)',
    backdropFilter: 'blur(40px)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
    transition: 'all 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  closeButton: {
    position: 'absolute',
    top: '1.5rem',
    right: '1.5rem',
    fontSize: '2.5rem',
    background: 'none',
    border: 'none',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    padding: '0.5rem',
    lineHeight: 1,
  },
  mobileNav: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '3rem',
    width: '100%',
  },
  mobileNavLink: {
    fontSize: '1.75rem',
    fontWeight: '800',
    color: 'var(--text-primary)',
    textDecoration: 'none',
    letterSpacing: '-0.02em',
    transition: 'color 0.2s',
  },
  mobileThemeToggle: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    transition: 'color 0.2s',
  },
  mobileLoginButton: {
    padding: '1.25rem 3.5rem',
    backgroundColor: 'var(--accent-teal)',
    color: '#fff',
    fontWeight: '800',
    fontSize: '1.25rem',
    borderRadius: '99px',
    border: 'none',
    marginTop: '2rem',
    boxShadow: '0 10px 30px rgba(5, 150, 105, 0.3)',
  }
};
