export const styles = {
  container: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(450px, 1fr))',
    gap: '4rem',
    width: '100%',
    maxWidth: '1600px',
    margin: '3rem 0 4rem 0',
    padding: '0 1rem',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  title: {
    fontSize: '1.25rem',
    fontWeight: '800',
    color: 'var(--accent-teal)',
    backgroundColor: '#ffffff',
    padding: '0.6rem 1.75rem',
    borderRadius: '99px',
    border: '1px solid rgba(5, 150, 105, 0.2)',
    boxShadow: '0 5px 15px rgba(0,0,0,0.05)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  newsCol: {
    display: 'flex',
    flexDirection: 'column',
  },
  newsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  newsCard: {
    display: 'flex',
    alignItems: 'flex-start',
    padding: '1.25rem 1.5rem',
    borderRadius: '24px',
    gap: '1rem',
  },
  newsIcon: {
    fontSize: '1.75rem',
    lineHeight: '1',
    paddingTop: '0.2rem',
  },
  newsContent: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  newsHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    marginBottom: '0.4rem',
  },
  newsTitle: {
    fontSize: '1.05rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
  },
  newsTime: {
    fontSize: '0.8rem',
    fontWeight: '600',
    color: 'var(--accent-teal)',
    whiteSpace: 'nowrap',
    marginLeft: '1rem',
  },
  newsDesc: {
    fontSize: '0.9rem',
    color: 'var(--text-secondary)',
    lineHeight: '1.4',
  },
  statusCol: {
    display: 'flex',
    flexDirection: 'column',
  },
  statusBox: {
    display: 'flex',
    flexDirection: 'column',
    borderRadius: '24px',
    padding: '0.5rem 1.5rem',
  },
  statusRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 0',
  },
  statusLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  statusIndicator: {
    width: '12px',
    height: '12px',
    borderRadius: '50%',
    flexShrink: 0,
  },
  destName: {
    fontSize: '1.05rem',
    fontWeight: '700',
    color: 'var(--text-primary)',
    minWidth: '120px',
  },
  destInfo: {
    fontSize: '0.9rem',
    fontWeight: '600',
    textAlign: 'right',
  },
  seeMoreLink: {
    display: 'inline-block',
    marginTop: '1.5rem',
    padding: '0.6rem 1.5rem',
    fontSize: '1rem',
    fontWeight: '800',
    color: '#ffffff',
    backgroundColor: 'var(--accent-teal)',
    borderRadius: '99px',
    textDecoration: 'none',
    boxShadow: '0 10px 20px rgba(5, 150, 105, 0.2)',
    transition: 'all 0.3s ease',
  }
};
