import React, { useState, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import DayCard from '../DayCard/DayCard';
import ItineraryFooter from '../ItineraryFooter/ItineraryFooter';
import { fetchItineraryData } from './ItineraryService';
import { styles } from './Itinerary.styles';

const Itinerary = () => {
  const location = useLocation();
  const navigate = useNavigate();
  
  const formData = location.state || {
    originCity: 'Lahore',
    destinationCity: 'Naran',
    startDate: new Date().toISOString().split('T')[0],
    duration: 7,
    modeOfTransport: 'By Car'
  };

  const [itineraryData, setItineraryData] = useState([]);
  const [baseCosts, setBaseCosts] = useState({ fuelTolls: 0, foodMisc: 0, jeepActivities: 0 });
  
  useEffect(() => {
    const loadData = async () => {
      const data = await fetchItineraryData(formData);
      setItineraryData(data.itinerary || []);
      setBaseCosts(data.baseCosts || { fuelTolls: 0, foodMisc: 0, jeepActivities: 0 });
    };
    loadData();
  }, [formData.originCity, formData.destinationCity, formData.startDate, formData.duration, formData.modeOfTransport]);

  const getMonthName = (dateStr) => {
    const d = new Date(dateStr);
    return d.toLocaleString('default', { month: 'long' });
  };

  const [selectedStays, setSelectedStays] = useState({});

  const [atBottom, setAtBottom] = useState(false);
  const bottomSentinelRef = React.useRef(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        setAtBottom(entry.isIntersecting);
      },
      { threshold: 0.1, rootMargin: '0px 0px 50px 0px' }
    );

    if (bottomSentinelRef.current) {
      observer.observe(bottomSentinelRef.current);
    }

    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (itineraryData.length === 0) return;
    const initialStays = {};
    itineraryData.forEach(day => {
      if (day.stays && day.stays.length > 0) {
        initialStays[day.id] = { type: day.stays[0].type, price: day.stays[0].price };
      }
    });
    setSelectedStays(initialStays);
  }, [itineraryData]);

  const handleStaySelect = (dayId, type, price) => {
    setSelectedStays(prev => ({
      ...prev,
      [dayId]: { type, price }
    }));
  };

  const totalAccommodation = Object.values(selectedStays).reduce((acc, curr) => acc + curr.price, 0);
  const totalCost = baseCosts.fuelTolls + baseCosts.foodMisc + baseCosts.jeepActivities + totalAccommodation;

  const currentCosts = {
    ...baseCosts,
    accommodation: totalAccommodation,
    total: totalCost
  };

  const getDayDateInfo = (dayIndex) => {
    const d = new Date(formData.startDate);
    d.setDate(d.getDate() + dayIndex);
    return {
      dateStr: d.toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
      dayOfWeek: d.toLocaleString('en-US', { weekday: 'long' })
    };
  };

  return (
    <div style={styles.pageBackground}>
      <div style={styles.container}>
        
        <div className="animate-slide-down delay-100" style={styles.headerArea}>
           <div style={styles.titleContainer}>
             <h1 style={styles.titleText}>{formData.originCity} <span style={{color: 'var(--text-tertiary)', margin:'0 4px'}}>→</span> {formData.destinationCity}</h1>
             <div style={styles.subtitleText}>
                {formData.duration} Days • {getMonthName(formData.startDate)} • {formData.modeOfTransport} • Generated by AI
             </div>
           </div>
        </div>

        <div className="animate-scale-up delay-200 glass-card" style={styles.overviewSection}>
           <h2 style={styles.sectionTitle}>Trip Overview</h2>
           <p style={styles.sectionSubtitle}>Total Distance: ~1,300 km (Round trip)</p>
           
           <div style={styles.overviewGrid}>
             <div className="glass-card" style={styles.overviewCard}>
                <div style={{color: '#10B981', marginBottom: '0.75rem'}}>
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 17h2c.6 0 1-.4 1-1v-3c0-.9-.7-1.7-1.5-1.9C18.7 10.6 16 10 16 10s-1.3-1.4-2.2-2.3c-.5-.4-1.1-.7-1.8-.7H5c-.6 0-1.1.4-1.4.9l-1.4 2.9A3.7 3.7 0 0 0 2 12v4c0 .6.4 1 1 1h2"></path><circle cx="7" cy="17" r="2"></circle><path d="M9 17h6"></path><circle cx="17" cy="17" r="2"></circle></svg>
                </div>
                <div style={styles.overviewCardLabel}>Fuel</div>
                <div style={styles.overviewCardValue}>Rs{Math.round(baseCosts.fuelTolls/1000)}k</div>
             </div>
             <div className="glass-card" style={styles.overviewCard}>
                <div style={{color: '#F59E0B', marginBottom: '0.75rem'}}>
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"></path><path d="M7 2v20"></path><path d="M21 15V2v0a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"></path></svg>
                </div>
                <div style={styles.overviewCardLabel}>Food</div>
                <div style={styles.overviewCardValue}>Rs{Math.round(baseCosts.foodMisc/1000)}k</div>
             </div>
             <div className="glass-card" style={styles.overviewCard}>
                <div style={{color: '#10B981', marginBottom: '0.75rem'}}>
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m8 3 4 8 5-5 5 15H2L8 3z"></path></svg>
                </div>
                <div style={styles.overviewCardLabel}>Jeep Hires</div>
                <div style={styles.overviewCardValue}>Rs{Math.round(baseCosts.jeepActivities/1000)}k</div>
             </div>
             <div className="glass-card" style={styles.overviewCard}>
                <div style={{color: '#F59E0B', marginBottom: '0.75rem'}}>
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"></path><path d="M12 18V6"></path></svg>
                </div>
                <div style={styles.overviewCardLabel}>Tolls</div>
                <div style={styles.overviewCardValue}>Included</div>
             </div>
           </div>
        </div>

        <div style={styles.daysList}>
          {itineraryData.map((day, index) => {
            const dateInfo = getDayDateInfo(index);
            const delayClass = `delay-${Math.min((index + 3) * 100, 1000)}`;
            return (
              <DayCard 
                key={day.id} 
                dayData={day} 
                dateStr={dateInfo.dateStr}
                dayOfWeek={dateInfo.dayOfWeek}
                onStaySelect={handleStaySelect}
                selectedStayType={selectedStays[day.id]?.type}
                className={`card-hover animate-slide-up ${delayClass}`}
              />
            );
          })}
        </div>

        <div ref={bottomSentinelRef} style={{ height: '20px' }} />

      </div>

      <ItineraryFooter costs={currentCosts} isAtBottom={atBottom} />
    </div>
  );
};

export default Itinerary;
