export const styles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    animation: 'fadeIn 0.5s ease-out',
  },
  container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    maxWidth: '550px',
    width: '90%',
    padding: '3rem 2rem',
    borderRadius: '24px',
  },
  iconWrapper: {
    position: 'relative',
    width: '80px',
    height: '80px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '2rem',
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    borderRadius: '50%',
  },
  sparkleOuter: {
    animation: 'pulse 2s infinite ease-in-out',
  },
  title: {
    fontSize: '2rem',
    fontWeight: '800',
    color: 'var(--text-primary)',
    marginBottom: '0.5rem',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    fontSize: '1rem',
    color: 'var(--text-secondary)',
    marginBottom: '3rem',
  },
  stepsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
    width: '100%',
    alignItems: 'flex-start',
    paddingLeft: '2rem',
  },
  stepItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    transition: 'all 0.3s ease',
  },
  statusIcon: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    border: '2px solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    transition: 'all 0.3s ease',
  },
  loadingRing: {
    width: '12px',
    height: '12px',
    borderRadius: '50%',
    border: '2px solid var(--accent-teal)',
    borderTopColor: 'transparent',
    animation: 'spin 1s linear infinite',
  },
  stepText: {
    fontSize: '1rem',
    textAlign: 'left',
  }
};
